### ISSUE TITLE
Update behavior...

### ISSUE THREAD

**Issue by merqlove** [piotrmurach/tty-spinner#10]
Hi Piotr, 
First, thanks for your work.
Just did some test case... This behavior feels wrong for me.
https://github.com/merqlove/tty-spinner/commit/113d6d9c1052fb6a23e97a5e3ef730381b82c798

```ruby
1) TTY::Spinner#update updates message content with custom token
     Failure/Error:
       expect(output.read).to eq([
         "\e[TEEEST '|",
         "\e[TEEEST /",
         "\e[TEEEST -",
         "\e[TEEEST \\",
         "\e[TEEEST |",
         "\e[TEEEST | done\n"
       ].join)

       expected: "\e[TEEEST '|\e[TEEEST /\e[TEEEST -\e[TEEEST \\\e[TEEEST |\e[TEEEST | done\n"
            got: ""                         EEEST | done
```

**Comment by piotrmurach** [comment]
Hi Alexander,

Thanks for using the library. So subsequent call to `update` wipes out a spinner output, I will take a look later today unless you fancy fixing it?

**Comment by merqlove** [comment]
👍 Yeah, something with buffer, i haven't seen much into the `gem` code, currently too busy. 

Just used workaround:
`spin.clear_line` before `spin.update` 👍 
Awesome! :)

**Comment by merqlove** [comment]
Maybe add this shortcut into the README? i can `PR`

**Comment by piotrmurach** [comment]
Not really sure how calling `spin.clear_line` fixed the issue for you. 

Essentially, after the spinner is stopped with `stop` call, internally the state changes to prevent further animation hence there was no output. I have added new api call `start` to allow resuming previously stopped spinner, for instance:
```ruby
5.times { spinner.spin }
spinner.stop('done')
spinner.start
5.times { spinner.spin }
spinner.stop('done')
.....
```

**Comment by piotrmurach** [comment]
Released `v0.4.0`.

**Comment by merqlove** [comment]
Yeah, it not helps so much, but anyway output feels & looks better on update...

The problem is i'm doing updates within`Futures` Pool, so it can't be stopped until awaited value or Error is received.

My process is:
```
    keywords.map do |k|
        Concurrent
            .future(thread_pool) do
              update_spin(spin, title: "Searching (keyword: #{k})")
              service.run(k)
            end
            .then do |r|
              update_spin(spin, title: "Searching (found image ID##{r.id})") if r
              r
            end
            .rescue { |e| ... }
     end
```

**Comment by piotrmurach** [comment]
If you call `update` when spinner is in spinning state then this will update current animation. With the new `start` method you can continue using update even after stop has been called, which solves the bug you have found. Does that help?
