### ISSUE TITLE
Updating titles with length shorten than previous one

### ISSUE THREAD

**Issue by merqlove** [piotrmurach/tty-spinner#11]

**Comment by piotrmurach** [comment]
> Better to test different lengths of the title. For example, first: 'task_abcdef'.
Because i found main problem is with updating title which length shorter than previous one.

**Comment by piotrmurach** [comment]
There is already `:clear` option for spinner to clear lines when stopped. So I've added clearing only when update called during the actual spinning state. This should fix the issue as the attached example demonstrates.

**Comment by piotrmurach** [comment]
Can you take master branch for a spin? - sorry :smile:

**Comment by merqlove** [comment]
yep, i have tried :) which method better? seems that `auto_spin` is successor of the `start`?
because with `start` i have no auto-spinning anymore :)))

**Comment by merqlove** [comment]
I can make short video with screenflow. With demonstration how both works at my side.

**Comment by merqlove** [comment]
Wow, now with autostart seems we have the best solution! 👍

**Comment by piotrmurach** [comment]
`start` doesn't do anything apart from resetting timer and unlocking the spinner. So if you need actual automatic spinning animation you can either use `autospin` or `run`. The `autospin` just starts infinite animation whereas, the `run` needs a block to execute and finishes when the block evaluates. There is always `spin` to manually spin the spinner the desired number of times. Your choice really.

**Comment by piotrmurach** [comment]
Are you happy with the fix for different lengths titles? If yes I will push new release.

**Comment by merqlove** [comment]
https://www.dropbox.com/s/f0wunnnet48cd0u/flickrage-with-spinner.mp4?dl=0

**Comment by piotrmurach** [comment]
I believe the flickering comes from title changing really quickly, not sure how this can be prevented?

**Comment by merqlove** [comment]
Maybe add call `spin` after merge? To kick the spinner?

**Comment by merqlove** [comment]
in 0.3.0 i'm had stack like:
spinner.`clear_...`
spinner.update
spinner.spin

**Comment by merqlove** [comment]
Yeah, it is :)
But with additional spinner here also artifacts...
Extended cast:
https://www.dropbox.com/s/ouki37vuhpua7hm/flickrage-with-spinner2.mp4?dl=0

**Comment by merqlove** [comment]
Yeah, it's ok now. Added `interval: 30` + `hide_cursor: true`

**Comment by piotrmurach** [comment]
Nice work! I'm wondering if `hide_cursor` option shouldn't be `true` by default?

**Comment by merqlove** [comment]
But how to show cursor back? It is completely hidden after program is exited:)))))))))

**Comment by merqlove** [comment]
I'm exited by error while spinning
:)

**Comment by piotrmurach** [comment]
If you call `stop`, `success` or `error` the cursor should be reset back. Otherwise, it's tough :)

**Comment by merqlove** [comment]
ok. i will do some callback for it :)

**Comment by piotrmurach** [comment]
Ok, I will need to push the release with fix for update as my time is running short?

**Comment by piotrmurach** [comment]
I would probably have `ensure` or `rescue` to make sure the spinner stops properly even when failing for whatever reason. On another note, regarding all tty libraries I'm working on I've setup [gitter account](https://gitter.im/piotrmurach/tty) where we can discuss things.
