### ISSUE TITLE
Multi Spinner API Review

### ISSUE THREAD

**Issue by austb** [piotrmurach/tty-spinner#16]
Currently the `TTY::Spinner::Multi` class supports `register`ing spinners you can start later.

1. `TTY::Spinner::Multi#initialize` should take arguments in the same form as `TTY::Spinner#initialize`
1. Should users be able to `register` a spinner with a block? (Note: we'd have to manage a thread for the block to run in)
1. Multi doesn't currently have a `spin` method (but it does have `auto_spin`). Is there a use case for adding `spin`?
1. Are there other methods that would be useful to users?

My feelings are
1. Yes, this should be standardized
1. There are so many different ways to use threads, and so many data races that can come of it, by obfuscating the fact that their code is running in threads we increase the chance for people to have problems.
1. I'd be fine adding this, do people ever pause their spinners? Other than that I can't think of a concrete use case.
1. I think the ability to tweak or customize how the top-level spinner and the sub-spinners display would be useful.
     - maybe with inset options? (where defaults are the spaces currently in the code)
```ruby
inset_opts = {
  insets: {
    top_level: "- "
    sub_spinners: "---- "
    last_spinner: "----> " # defaults to sub_spinners if not provided
  }
}

# This is not how they are currently initialized, but how they would be under #1
TTY::Spinner::Multi.new("[:spinner] top level", inset_opts)
```

**Comment by piotrmurach** [comment]
Thank you for listing these. I've opened separate issues for each point:
1. Agree & opened new [issue](https://github.com/piotrmurach/tty-spinner/issues/19)
2. I kind of feel that this would be one of the ways to create multiple spinners. It seems to me to be a more programmatic way of registering similar indeterminate tasks. For example, you could get enumerable of files and create spinners for each that start when multispinner is started(i guess we would need to add `#start`) that need to be downloaded in separate jobs and monitored when all are completed/errored. [issue](https://github.com/piotrmurach/tty-spinner/issues/20)
3. Agree spin seems awkward for multi spinners, but having `#pause` and `#resume` may be an interesting addition. I can see these potentially being useful for single spinner and multi spinner. I'm not sure if people are dying to have this feature though :smile: [issue](https://github.com/piotrmurach/tty-spinner/issues/21)
4. Agree, though my preference in naming would be to use `indent` & `style` in place of `insets` [issue](https://github.com/piotrmurach/tty-spinner/issues/18)

What do you reckon?
