### ISSUE TITLE
Multi Spinner documentation

### ISSUE THREAD

**Issue by austb** [piotrmurach/tty-spinner#17]
`TTY::Spinner::Multi` needs documentation

- [x] Document the methods in code
- [x] Add docs to README
- [x] Ensure there is an explanation of how passing options to `TTY::Spinner::Multi` will in turn affect spinners created with `#register`

**Comment by austb** [comment]
Am I missing any docs we should be sure to have?

**Comment by piotrmurach** [comment]
Nope, I think that's all. I think the `TTY::Spinner::Multi` api calls could be described in new section 5. I would definietly create a simple example of using multi spinners in the Usage section as well for people who want to get started quickly. Do you fancy taking a stab at it as well?

**Comment by austb** [comment]
Yep! I can work on that 👍
