### ISSUE TITLE
Displaying multi spinners in a tree format

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-spinner#18]
Ability to display spinners in a tree like format. By default, if the multispinner is created with top level spinner, all the child spinners are printed in a tree like format. However, if no top level spinner is provided, all spinners are displayed without any decoration. The formatting can follow similar symbols to [tty-tree](https://github.com/piotrmurach/tty-tree#1-usage)

The format can be configured by providing the following option:
```ruby
indent: 2, # indentation depth
style: { # formatting style
  top: '--',
  mid: '|',
  bottom: '--'
}
```

**Comment by austb** [comment]
@piotrmurach so with the indentation depth number you added, do you envision that being used to change `'|'` to `'| '`

**Comment by piotrmurach** [comment]
@austb I liked your example styling and changed multi spinner to apply default unicode styling with ascii fallback on windows. Added [usage example](https://github.com/piotrmurach/tty-spinner#1-usage) and [:style docs](https://github.com/piotrmurach/tty-spinner#54-style).
