### ISSUE TITLE
Bouncing ball multi spinner bug

### ISSUE THREAD

**Issue by ordinaryzelig** [piotrmurach/tty-spinner#27]
I'm using a multi-spinner with bouncing ball format. Seems to be a small bug with the redrawing on completion.

```ruby
require 'tty-spinner'

multi = TTY::Spinner::Multi.new(
  "[:spinner]",
  :hide_cursor => true,
  :format => :bouncing_ball
)

2.times do |idx|
  multi.register("[:spinner] Cancellation id #{idx} (status: :status)") do |spinner|
    loop do
      sleep 1
      n = rand 5
      spinner.success and break if n == 0
      spinner.update(:status => 'blah' * n)
    end
  end
end

multi.auto_spin
```

Example video: https://cl.ly/1j2r1I233i2B

**Comment by piotrmurach** [comment]
Hey Jared, 

Long time no see 😄 

Thank you for this detailed bug report! I'll take a look.

**Comment by ordinaryzelig** [comment]
Hey. Long time indeed!

My pleasure. 😄

**Comment by piotrmurach** [comment]
This is fixed in master. It was super important issue as the bug was connected with pretty much any spinner that was stopped, it so happened that majority of spinners didn't change content/width and hence they looked fine when done. Will release shortly!
