### ISSUE TITLE
tty-spinner affecting stderr of Ruby scripts

### ISSUE THREAD

**Issue by KrauseFx** [piotrmurach/tty-spinner#28]
A _fastlane_ user just reported an issue that they can't capture `stderror` any more, once the `tty-spinner` is enabled: https://github.com/fastlane/fastlane/issues/11498#issuecomment-356330515

I read this section of the README

```
3.8 :output
To change where data is streamed use :output option like so:

spinner = TTY::Spinner.new(output: $stdout)
The output stream defaults to stderr.
```

Could you tell us more about why the default is `stderr`, and why `$stdout` shouldn't be default? I don't know too much about this myself unfortunately

**Comment by piotrmurach** [comment]
Hi Felix,

I would assume as much, `tty-spinner` outputting to stderr would probably overwrite all the other debug stuff. As far as decision goes, I picked stderr similar to a lot of unix tools, for instance, `git` prints its output by default to stderr. There isn't a strong argument for keeping it this way and I'm happy to change it to stdout by default. One of the reasons I've provided `:output` option was to let people decide what's best in their specific use cases.

**Comment by piotrmurach** [comment]
In terms of output nothing will change, and probably in majority of use cases nobody won't even notice. Is there any risk involved? Probably yes, someone maybe relying on the fact that stderr is used by default similar to fastlane reported issue. But having changelog should help explain the change. 

We should probably look at this from a broader perspective. Spinners are generally considered a notification for the user to let them know what the application is doing. The error stream should probably be left for special conditions signifying that something wrong is going on. I think this gem should be a good terminal citizen and not pollute error logs. What are your thoughts? 

Of course, this would need to be treated as a breaking change and I would need to release `v0.8.0`.

**Comment by piotrmurach** [comment]
I had a think about this issue and realised that whether it's `stdout` or `stderr` is irrelevant. What really matters is the fact that the spinner outputs to no-tty device during redirection, in this instance, another file, it just so happens to be error stream. The remedy would be to detect where the output is going. There is no point rendering spinners outside of terminal as they produce tons of gibberish.

**Comment by piotrmurach** [comment]
@KrauseFx I've expanded [:output docs](https://github.com/piotrmurach/tty-spinner#38-output) to explain current behaviour. The spinner only outputs to a console, so redirecting to a file will contain no output at all. I decided to stay with `stderr` as the default output stream based on a bit of reading and research. The intention is correct for using `stderr` when providing diagnostic information for the terminal application as intended by the creator of Unix system. The error pipe is quite often used for informational purposes including help messages. The famous utility `grep` command when run without arguments outputs to `stderr`.

**Comment by KrauseFx** [comment]
Awesome, thanks. Appreciate your help 👍

**Comment by piotrmurach** [comment]
Hi @RoUS,

First of all, would you have time to open an issue, please? My preference would be to keep this old issue as is and start a new discussion thread.

I'm not familiar with a practice of sending information when the output is not tty device. Do you have an example of unix utility that does it?
