### ISSUE TITLE
Thread deadlock problem

### ISSUE THREAD

**Issue by bluegod** [piotrmurach/tty-spinner#29]
I have a multithreaded Ruby app that is using `tty-spinner` 0.8.0.

I get a `join': No live threads left. Deadlock? (fatal)` that I've found related to `tty-spinner`, and would appreciate some help. Each thread is registering a new spinner on the main multi spinner, and use it to update/spin afterwards. The only shared state across threads is the multi spinner. The threads only update their own spinner.

The deadlock happens mainly when registering a new spinner (which is done concurrently, other threads may update their own spinner or new threads may create new ones). Stacktrace:

```
/Users/james/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:187:in `lock'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:187:in `mon_enter'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:212:in `mon_synchronize'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner.rb:475:in `execute_on_line'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner.rb:502:in `write'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner.rb:360:in `redraw_indent'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner/multi.rb:92:in `block (2 levels) in register'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner/multi.rb:92:in `each'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner/multi.rb:92:in `block in register'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/james/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/tty-spinner-0.8.0/lib/tty/spinner/multi.rb:86:in `register'
```

Changing this line: https://github.com/piotrmurach/tty-spinner/blob/v0.8.0/lib/tty/spinner.rb#L477

to 

```ruby
@row ||= @multispinner.row + 1
```

fixes the problem, but it could be a red herring.

**Comment by piotrmurach** [comment]
Hi James,

Thanks for using the library and reporting this issue!

Would you have time to put together an example that replicates this issue? The issue maybe what you suggested or it maybe totally different problem all together.

**Comment by bluegod** [comment]
Hi Piotr,

Thanks for your prompt response!

> Would you have time to put together an example that replicates this issue? 

Of course: https://gitlab.com/snippets/1713033

>  The issue maybe what you suggested or it maybe totally different problem all together.

Yes, it can certainly mean I'm just missing something! Thanks again.
