### ISSUE TITLE
DEC_TCEM is not defined

### ISSUE THREAD

**Issue by benklop** [piotrmurach/tty-spinner#38]
I'm getting an error when creating multiple spinners,
``gems/tty-spinner-0.9.1/lib/tty/spinner.rb:375:in `redraw_indent': uninitialized constant TTY::Spinner::DEC_TCEM (NameError)``. I've looked, and i don't actually see it defined anywhere in the code:

https://github.com/piotrmurach/tty-spinner/blob/a63f2df6acd0811c66d0b548ebcd7626b3cfc150/lib/tty/spinner.rb#L375

**Comment by piotrmurach** [comment]
Released `v0.9.2` with your patch. Thanks!
