### ISSUE TITLE
Feature Request: Allow to explicitly mark some state or indicator

### ISSUE THREAD

**Issue by dipanm** [piotrmurach/tty-spinner#46]
Currently, the spinners have standard animation based on the `:format` given and the API explicitly allows `success_mark` and `error_mark` set when the corresponding method is called. 

One of the useful additions could be to allows additional marks (with paused/stopped spinners) which can be informative. e.g. _"Waiting for external inputs"_ , _"Job getting ready before work starts"_, _"job running but there are warnings"_ etc.; these are neither a success nor error/failures. We need not define so many custom states. Just allow for explicitly set the mark 

so here are the changes can be made
`spinner.stop` can be changed to `spinner.stop(mark: "!")`  or 
`spinner.pause` can be changed to `spinner.pause(mark: "#")` 
 
 The second argument can be optional.

**Comment by piotrmurach** [comment]
Hi Dipan 👋 

Thanks for using `tty-spinner`.

This sounds like a good suggestion. I'm in favour of letting users override dynamically stop and pause markers. Would you have time to submit PR with tests?

**Comment by dipanm** [comment]
Thank you so much for this new functionality. `tty-spinner` is indeed cool!
